on: [discussion, discussion_comment]

jobs:
  testing_backups:
    runs-on: ubuntu-latest
    name: A job to test backups
    steps:
      - name: Backup Testing
        id: backup
        uses: Pandapip1/gh-discussions-backup@0.0.1-testing1
        with:
          token: ${{ github.token }}
      - name: Get the output
        run: echo "${{ steps.backup.outputs.backup }}"
